name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integrity:
    name: integrity
    permissions:
      contents: read
    uses: Sulamtech/devsecops-poc-workflows/.github/workflows/reusable-caller-integrity.yml@56c4aa8ca8d903657f51ed396afe9467611cf095

  governance:
    name: governance
    needs: integrity
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      issues: read
      pull-requests: read
    uses: Sulamtech/devsecops-poc-workflows/.github/workflows/reusable-pr-governance.yml@56c4aa8ca8d903657f51ed396afe9467611cf095

  tests:
    name: tests
    needs: integrity
    permissions:
      contents: read
    uses: Sulamtech/devsecops-poc-workflows/.github/workflows/reusable-node-ci.yml@56c4aa8ca8d903657f51ed396afe9467611cf095
    with:
      node-version: "22"

  security:
    name: security
    needs: integrity
    permissions:
      contents: read
      pull-requests: read
    uses: Sulamtech/devsecops-poc-workflows/.github/workflows/reusable-security.yml@56c4aa8ca8d903657f51ed396afe9467611cf095
    with:
      image-name: devsecops-poc-nextjs
